[package]
name = "alta-infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
alta-kernel = { workspace = true }
alta-application = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
config = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
